apiVersion: v1
kind: Service
metadata:
  name: nginx-node
spec:
  selector:
    app: apps
  ports:
  - port: 9003
    targetPort: 80
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: multitool-node
spec:
  selector:
    app: apps
  ports:
  - port: 9004
    targetPort: 81
  type: NodePort


