apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: apps
  ports:
  - port: 9001
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: multitool-service
spec:
  selector:
    app: apps
  ports:
  - port: 9002
    targetPort: 81


